### ISSUE TITLE
media queries redundancy

### ISSUE THREAD

**Issue by Sara-Samer** [mustafa-mahmoud203/udemy#1]
https://github.com/mustafa-mahmoud203/udemy/blob/feab592155c1ee05138f3fbe1c810e3dd32a2ebc/media-query.css#L1-L33

using media queries with minimal pixel differences like that is not optimal 
please refer to the standard media queries breakpoints

**Comment by mustafa-mahmoud203** [comment]
Well I solved these problems now ,I hope they are correct ^_^
